### PR TITLE
added a github workflow

### PR DESCRIPTION
**Pull request by nimboya**
Added test on the Github Workflow

### CODE REVIEW

**Review by haroldsphinx — APPROVED** [review]

**Comment by seunlanlege** [comment]
@vjdmhd can you please check what is up with the code?

**Comment by vjdmhd** [comment]
@nimboya We need to tun `go mod tidy` before `go test`, This is because the test fails

**Comment by vjdmhd** [comment]
@nimboya Please rename it to `added mod tidy` not tiny

**Comment by nimboya** [comment]
> @nimboya We need to tun `go mod tidy` before `go test`, This is because the test fails

**Comment by nimboya** [comment]
Thanks @vjdmhd, it has been added and test ran successfully

**Pull request merged**
